apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: python:3.7.13-alpine
        command:
        - python3
        args:
        - |+
          -c
          print("hello")
      restartPolicy: Never
